on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  windows-binary:
    runs-on: windows-2022
    strategy:
      matrix:
        VER: [v143]
        GEN: [Visual Studio 17 2022]
        BIN: [x64, x86]

    steps:
    - name: Checkout Test-Applications
      uses: actions/checkout@v2

    - name: Create Build Environment
      shell: pwsh
      run: |
        # Parallelize MSBuild across projects
        [Environment]::SetEnvironmentVariable('UseMultiToolTask', 'true', [EnvironmentVariableTarget]::User)

    - name: Configure
      shell: pwsh
      run: |
        $BIN = if('${{matrix.BIN}}' -eq 'x86') {'Win32'} else {'x64'}
        & cmake `
          -G '${{matrix.GEN}}' `
          -A ${BIN} `
          -T ${{matrix.VER}} `
          -S "${env:GITHUB_WORKSPACE}\CPP-Filesystem" `
          -B "${env:GITHUB_WORKSPACE}\CPP-Filesystem\build" `
          -D CPACK_SOURCE_IGNORE_FILES="/\\.git/"

    - name: Build
      shell: pwsh
      run: |
        & cmake `
          --build "${env:GITHUB_WORKSPACE}\CPP-Filesystem\build" `
          --config Release `
          -- `
          /verbosity:minimal `
          /maxCpuCount `
          /noLogo

    - name: Install
      shell: pwsh
      run: |
        & cmake `
          --install "${env:GITHUB_WORKSPACE}\CPP-Filesystem\build" `
          --prefix "${env:GITHUB_WORKSPACE}\CPP-Filesystem\install" `
          --config Release

    - name: Package Binary
      shell: pwsh
      run: |
        $BIN = if('${{matrix.BIN}}' -eq 'x86') {'win32'} else {'win64'}
        & cpack `
          --config "${env:GITHUB_WORKSPACE}\CPP-Filesystem\build\CPackConfig.cmake" `
          -G ZIP `
          -C Release `
          -B "${env:GITHUB_WORKSPACE}\CPP-Filesystem\package"
        Rename-Item "${env:GITHUB_WORKSPACE}\CPP-Filesystem\package\CPP-Filesystem-0.1.1-${BIN}.zip" "CPP-Filesystem-0.1.1-${{matrix.BIN}}.zip"

    - name: Release Binary
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          CPP-Filesystem/package/CPP-Filesystem-0.1.1-${{matrix.BIN}}.zip

  source:
    name: Source Release (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        OS: [ubuntu-20.04, windows-2022]

    steps:
    - name: Checkout Test-Applications
      uses: actions/checkout@v2

    - name: Configure
      shell: pwsh
      run: |
        & cmake `
          -S "${env:GITHUB_WORKSPACE}/CPP-Filesystem" `
          -B "${env:GITHUB_WORKSPACE}/CPP-Filesystem/build" `
          -D CPACK_SOURCE_IGNORE_FILES="/\\.git/"

    - name: Package Source
      shell: pwsh
      run: |
        Get-ChildItem Env:/
        Get-ChildItem "${env:GITHUB_WORKSPACE}/CPP-Filesystem"
        & cpack `
          --config "${env:GITHUB_WORKSPACE}\CPP-Filesystem\build\CPackSourceConfig.cmake" `
          -G (if('${{matrix.OS}}' -match 'windows') {'ZIP'} else {'TGZ'}) `
          -C Release `
          -B "${env:GITHUB_WORKSPACE}/CPP-Filesystem/package"

    - name: Release Source
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          CPP-Filesystem/package/CPP-Filesystem-0.1.1-Source.*